### ISSUE TITLE
"Colour"

### ISSUE THREAD

**Issue by LoganDark** [Exerro/Flare#1]
Every single library!!!
EVERY SINGLE LIBRARY.

Every single library has to use the NON-CONFIGURABLE `Colour` spelling.

I'm American, so we spell it `color` here, and seeing it spelt like `colour` with absolutely no option to change it pisses me off.

**Comment by viluon** [comment]
Flare hasn't seen a commit for almost two years. This project is long dead. However, it wouldn't be too hard to replace all occurrences of "colour" with "color" (with `sed`, for example).

I feel your pain, it would be best if the library allowed both ways of spelling. Personally though, I'm not a native speaker, and I think american English sucks. If only one option is available, it should be the mighty royal one. (Oh and @Exerro is British.)

**Comment by LoganDark** [comment]
"Mighty royal"

It's so much better because `colour` has a U in it. And because `centre` has a typo (on purpose™)

Sarcasm aside, by the use of `colour` I can tell that @Exerro is British. And yes, I could just use something like `sed` to replace all the `colour`s with `color`, but that just feels hacky to me. I prefer an official solution.

**Comment by Exerro** [comment]
As @viluon pointed out, this is pretty long dead, so I won't do anything about it. Do you actually use this? I guess having an option for `color` is good, but you can just do `local color = colour` at the beginning, so I'd hardly count it as an important feature.

**Comment by LoganDark** [comment]
I won't, no, since the docs aren't that interesting and there are no tutorials I could find. And no, I can't do that, because there are a shit ton more variables/attributes/properties that have `colour` in them.

**Comment by Exerro** [comment]
Fair enough, I'd recommend Titanium if you need a framework. I didn't realise you were referring to attributes too, I've not used this for ages. I'll keep it in mind for the next framework I make.

**Comment by LoganDark** [comment]
Fair enough, I was already trying to use Titanium earlier anyway. Shouldn't
be too hard to figure out I'm most likely going to use it for my next
project
